networks:
  boursenet:
    driver: bridge

services:
  db:
    image: timescale/timescaledb:latest-pg16
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - "5432:5432"
    networks:
      - boursenet
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=ricou
      - POSTGRES_PASSWORD=monmdp
    volumes:
      - /Users/abdoulayebalde/MajeurImage/pythonBigData/BigData/baseDonnée:/var/lib/postgresql/data/timescaledb
    healthcheck:
        test: ["CMD-SHELL", "pg_isready bourse"]
        interval: 6s
        timeout: 3s
        retries: 5

  analyzer:
    image: my_analyzer
    depends_on:
        - db
    networks:
      - boursenet
    volumes:
      - /Users/abdoulayebalde/MajeurImage/pythonBigData/BigData/boursorama:/home/bourse/data/

  dashboard:
    image: my_dashboard
    networks:
      - boursenet
    ports:
      - "8050:8050"
